### PR TITLE
Smoother onboarding

### LINKED ISSUE #35: Protect against disabled agent
Was debugging something in production and had to disable optics agent to identify cause of issue. The agent seems to not deal well with being half integrated:

If the agent is just instantiated without being hooked up in middleware I get this error:
[node_modules/optics-agent/dist/Report.js:273] EEE [TypeError: Cannot read property 'getTypeMap' of undefined]

If the agent is instantiated and `instrumentSchema` is called, but not put into middleware, all requests will break with:
[lib/api/controllers/graphql/graphql.jsx:28] Cannot read property 'startHrTime' of undefined

### PR DESCRIPTION
**Pull request by n1mmy**
- Detect and warn instead of crashing on missing configuration.
- Crash immediately if `configureAgent` is called incorrectly.
- Disable the agent when no API key is set.

Fixes #35

### CODE REVIEW

File: src/Agent.js [hunk 1]
```diff
@@ -44,6 +44,15 @@ export default class Agent {
     this.reportTraces = reportTraces !== false;
     this.reportVariables = reportVariables !== false;
 
+    // Ensure we have an api key. If not, print and disable the agent.
+    if (!this.apiKey) {
+      this.debugFn(
+        'Optics agent disabled: no API key specified.',
+        'Set the apiKey option or set the OPTICS_API_KEY environment variable.'
+      );
+      this.disabled = true;
```
Comment (glasser) [inline src/Agent.js]: Please set fields consistently in the constructor: ie, this field should be false or true, not absent or true.  It makes it much easier to understand what the type of an object is.

Also, along these lines: I'd suggest doing this either after initializing all fields to some value, or immediately after initializing apiKey and debugFn. It's a little weird to have an object that has a semi random subset of fields initialized!

File: src/Agent.js [hunk 2]
```diff
@@ -44,6 +44,15 @@ export default class Agent {
     this.reportTraces = reportTraces !== false;
     this.reportVariables = reportVariables !== false;
 
+    // Ensure we have an api key. If not, print and disable the agent.
+    if (!this.apiKey) {
+      this.debugFn(
+        'Optics agent disabled: no API key specified.',
+        'Set the apiKey option or set the OPTICS_API_KEY environment variable.'
```
Comment (glasser) [inline src/Agent.js]: "the apiKey option to configureAgent" (or maybe a different preposition)... since there's no stack trace here.

File: src/Agent.js [hunk 3]
```diff
@@ -44,6 +44,15 @@ export default class Agent {
     this.reportTraces = reportTraces !== false;
     this.reportVariables = reportVariables !== false;
 
+    // Ensure we have an api key. If not, print and disable the agent.
+    if (!this.apiKey) {
+      this.debugFn(
```
Comment (glasser) [inline src/Agent.js]: A little odd that you are adding uses of debugFn immediately after dropping it from the README as "not implemented"?

File: src/DefaultAgent.js [hunk 4]
```diff
@@ -12,13 +12,9 @@ let defaultAgent = null;
...
   if (defaultAgent) {
-    // XXX This error message is confusing if you only call configureAgent once
-    //     but call another function before it
-    // XXX This is a pretty bad problem that means your configuration won't work
-    //     --- wouldn't throwing be better?
-    //     https://github.com/apollostack/optics-agent-js/issues/17
-    defaultAgent.debugFn('Error: default agent already configured.');
-    return;
+    throw new Error(
+      'Optics Agent configuration already set. Make sure `configureAgent` is called only once, and before any calls to `middleware` or `instrumentSchema`.'
```
Comment (glasser) [inline src/DefaultAgent.js]: Probably worth mentioning at least instrumentHapiServer if not context.

File: src/Agent.js [hunk 5]
```diff
@@ -65,26 +74,42 @@ export default class Agent {
...
+      return {};
+    }
     return newContext(req, this);
   }
 
   // XXX This is not part of the public API.
   //     https://github.com/apollostack/optics-agent-js/issues/51
   sendReport() {
+    if (!this.schema) {
+      this.debugFn('Optics agent: schema not instrumented. Make sure `instrumentSchema` is called.');
```
Comment (glasser) [inline src/Agent.js]: Won't this print a lot? I thought you were concerned about spamminess.

Also nicer to use active voice: "Make sure to call `instrumentSchema`".

File: src/Instrument.js [hunk 6]
```diff
@@ -266,14 +279,27 @@ export const instrumentSchema = (schema) => {
...
-    // This shouldn't happen. The middleware is supposed to have
-    // already added the _opticsContext field. We make a new context
-    // as a safety belt here. It may not work, but at least it won't
-    // crash.
-    context = {};
+    // This happens if the middleware isn't run correctly.
+
+    // XXX this will print once per request! Maybe add a "warn once"
+    // feature to print only once.
+    agent.debugFn('Optics context not found. Make sure optics middleware is installed.');
```
Comment (glasser) [inline src/Instrument.js]: Optics should always be capitalized?

File: src/Agent.js (hunk 2 above)
Comment (n1mmy) [inline src/Agent.js]: Wilco.

File: src/Agent.js (hunk 1 above)
Comment (n1mmy) [inline src/Agent.js]: Wilco.

File: src/Agent.js (hunk 5 above)
Comment (n1mmy) [inline src/Agent.js]: It will report once per minute, which doesn't seem too spammy. I'm more concerned about once per request spam (which I did introduce with a comment to come back to) or once per resolver spam (which I decided was a bit too far to introduce w/o the warn once functionality)

Good call on rewording.

File: src/DefaultAgent.js (hunk 4 above)
Comment (n1mmy) [inline src/DefaultAgent.js]: Yup. Wilco

**Comment by n1mmy** [comment]
@glasser changes addressed. ready for re-review.

File: src/Proto.js [hunk 7]
```diff
@@ -7,9 +7,14 @@
...
 
 // Copied and pasted from https://github.com/apollostack/optics-agent
-// instead of using a seperate file so we can load w/o doing async I/O
+// instead of using a separate file so we can load w/o doing async I/O
 // at startup. This could be done with a babel plugin at compile time
 // instead.
+//
+// XXX As noted in
+// https://github.com/apollostack/optics-agent-js/issues/55 simply
+// doing `readFileSync` may be the same performance as require as
```
Comment (glasser) [inline src/Proto.js]: last "as" => "and"

Comment (glasser) [inline src/Proto.js]: last "as" => "and"
